server:
  port: 8093
logging:
  config: classpath:logback-spring.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8094/xxl-job-admin #调度中心地址
    accessToken: #执行器通讯token
    executor:
      appname: springboot-xxl-job #执行器名称，执行器心跳注册分组依据，为空时关闭自动注册
      address: #执行器注册地址
      ip: #执行器IP
      port: 9999 #执行器端口号
      logpath: /data/applogs/xxl-job/jobhandler #执行器运行日志文件存储路径
      logretentiondays: 30 #日志文件保存天数