server:
  port: 8085

spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.11:3306/springboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 10 #最小空闲连接，默认10
      maximum-pool-size: 20 #最大连接数
      idle-timeout: 600000 #空闲连接超时时间，默认600000(10分钟)
      max-lifetime: 540000 #连接最大存活时间，默认30分钟
      connection-timeout: 60000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #测试连接是否可用查询语句
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.xlhj.mybatis: debug

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.xlhj.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql