server:
  port: 8095
spring:
  application:
    name: springboot-quartz
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.11:3306/springboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: qaz123456
    hikari:
      minimum-idle: 10 #最小空闲连接，默认10
      maximum-pool-size: 20 #最大连接数
      idle-timeout: 600000 #空闲连接超时时间，默认600000(10分钟)
      max-lifetime: 540000 #连接最大存活时间，默认30分钟
      connection-timeout: 60000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #测试连接是否可用查询语句
      auto-commit: true
      pool-name: HikariCP
  quartz:
    job-store-type: jdbc #将任务保存到数据库
    wait-for-jobs-to-complete-on-shutdown: true #程序结束时会等待quartz相关内容结束
    overwrite-existing-jobs: true #启动时更新已存在的job
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler #实例名
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool #连接池
            threadCount: 10
            threadPriority: 5 #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true