server:
  port: 8115
spring:
  application:
    name: springboot-zookeeper
zookeeper:
  enabled: true
  server: 127.0.0.1:2181
  namespace: springboot-zookeeper
  digest: rt:rt #zkCli.sh acl命令addauth digest mpush
  sessionTimeoutMs: 1000 #会话超时时间，单位ms
  connectionTimeoutMs: 6000 #连接创建超时时间，单位ms
  maxRetries: 3 #最大重试次数
  baseSleepTimeMs: 1000 #初始sleep时间，单位ms